apiVersion: apps/v1
kind: Deployment
metadata:
  name: dal_app
  namespace: benny3644-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dal_app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongodb
          image: registry.access.redhat.com/rhscl/mongodb-26-rhel7
          ports:
            - containerPort: 8000
          env:
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
            - name: MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: db
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-pv-claim
